spring.application.name=mecanica

spring.datasource.url=jdbc:postgresql://localhost:5432/mecanica
spring.datasource.username=mecanica
spring.datasource.password=mecanica
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

jwt.secret=${JWT_SECRET:2hub0pa0lzMheKg7yF_yfQa-4O2Zrj8vsFb1-K9aqsxzcvY9U56cmxER2KveU9B5}
jwt.expiration=${JWT_EXPIRATION:86400000}