spring.application.name=mecanica

spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=${JWT_SECRET:2hub0pa0lzMheKg7yF_yfQa-4O2Zrj8vsFb1-K9aqsxzcvY9U56cmxER2KveU9B5}
jwt.expiration=${JWT_EXPIRATION:86400000}
